[package]
name = "thread-art"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
image = "0.24.5"
rayon = "1.10"
svg = "0.17.0"
palette = "0.7.6"
quantette = "0.3.0"
